"use client";

import { useState } from "react";

interface Props {
  siteId: string;
  siteName: string;
  siteDomain: string;
  contactEmail: string;
  contactName: string;
  lastScanViolations: number | null;
  lastScanAt: string | null;
  currentStatementUrl: string | null;
}

function generateHtml(opts: {
  siteName: string;
  siteDomain: string;
  contactEmail: string;
  contactName: string;
  conformanceLevel: string;
  reviewDate: string;
  limitations: string;
  lastScanViolations: number | null;
}): string {
  const { siteName, siteDomain, contactEmail, contactName, conformanceLevel, reviewDate, limitations, lastScanViolations } = opts;

  const statusNote =
    lastScanViolations === null
      ? "An automated accessibility scan has not yet been performed."
      : lastScanViolations === 0
      ? "The most recent automated WCAG scan found no violations."
      : `The most recent automated WCAG scan found ${lastScanViolations} potential violation(s). We are actively working to resolve them.`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Accessibility Statement — ${siteName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #1a1a1a; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    h2 { font-size: 1.25rem; margin-top: 2rem; color: #0066cc; border-bottom: 1px solid #e5e7eb; padding-bottom: 0.25rem; }
    p, li { margin-bottom: 0.75rem; }
    ul { padding-left: 1.5rem; }
    a { color: #0066cc; }
    footer { margin-top: 3rem; font-size: 0.85rem; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 1rem; }
  </style>
</head>
<body>
  <h1>Accessibility Statement</h1>
  <p>This statement applies to: <strong><a href="https://${siteDomain}">${siteDomain}</a></strong></p>
  <p>Last reviewed: <strong>${reviewDate}</strong></p>

  <h2>Our Commitment</h2>
  <p>${siteName} is committed to ensuring digital accessibility for people with disabilities. We continually improve the user experience for everyone and apply relevant accessibility standards.</p>

  <h2>Conformance Status</h2>
  <p>We aim for <strong>WCAG 2.1 Level ${conformanceLevel}</strong> conformance, as defined by the Web Content Accessibility Guidelines (WCAG) 2.1. ${conformanceLevel === "AA" ? "This meets the requirements of the European Accessibility Act (EAA) and EN 301 549." : ""}</p>
  <p>${statusNote}</p>

  <h2>Technical Specifications</h2>
  <p>This website relies on the following technologies for conformance:</p>
  <ul>
    <li>HTML</li>
    <li>CSS</li>
    <li>JavaScript</li>
  </ul>
  <p>An accessibility widget (powered by Inculva) is embedded on this site to provide on-demand assistive features including text resizing, high contrast, dyslexia-friendly fonts, keyboard navigation, screen reader support, and more.</p>

  ${limitations ? `<h2>Known Limitations</h2>\n  <p>${limitations.replace(/\n/g, "</p>\n  <p>")}</p>` : ""}

  <h2>Feedback and Contact</h2>
  <p>We welcome your feedback on the accessibility of ${siteName}. If you experience accessibility barriers, please contact us:</p>
  <ul>
    ${contactName ? `<li><strong>Name:</strong> ${contactName}</li>` : ""}
    <li><strong>Email:</strong> <a href="mailto:${contactEmail}">${contactEmail}</a></li>
    <li><strong>Website:</strong> <a href="https://${siteDomain}">${siteDomain}</a></li>
  </ul>
  <p>We try to respond to accessibility feedback within <strong>2 business days</strong>.</p>

  <h2>Enforcement Procedure</h2>
  <p>If you are not satisfied with our response, you may contact the relevant national supervisory body responsible for enforcing the European Accessibility Act in your country.</p>

  <footer>
    <p>This accessibility statement was prepared in accordance with <a href="https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32019L0882">Directive (EU) 2019/882</a> (European Accessibility Act) and WCAG 2.1.</p>
    <p>Statement generated by <a href="https://inculva.com">Inculva</a> on ${new Date().toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric" })}.</p>
  </footer>
</body>
</html>`;
}

export function StatementClient({
  siteId,
  siteName,
  siteDomain,
  contactEmail,
  contactName,
  lastScanViolations,
  lastScanAt,
  currentStatementUrl,
}: Props) {
  const today = new Date().toISOString().slice(0, 10);

  const [form, setForm] = useState({
    contactEmail,
    contactName,
    conformanceLevel: "AA",
    reviewDate: today,
    limitations: "",
  });

  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [preview, setPreview] = useState(false);
  const [copied, setCopied] = useState(false);

  const hostedUrl = `https://app.inculva.com/s/${siteId}`;

  function copyHostedUrl() {
    void navigator.clipboard.writeText(hostedUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  const html = generateHtml({ ...form, siteName, siteDomain, lastScanViolations });

  function downloadHtml() {
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `accessibility-statement-${siteDomain}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function saveUrl() {
    setSaving(true);
    try {
      await fetch(`/api/sites/${siteId}/statement`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: currentStatementUrl }),
      });
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="space-y-6">
      {/* Hosted URL banner */}
      <div className="bg-green-50 dark:bg-green-950 border border-green-200 dark:border-green-800 rounded-2xl p-5 space-y-3">
        <div>
          <h3 className="font-semibold text-green-900 dark:text-green-200 mb-1">Hosted Accessibility Statement</h3>
          <p className="text-sm text-green-700 dark:text-green-300">
            Inculva hosts your accessibility statement automatically — no self-hosting required. Copy the URL below and use it as your <code className="bg-green-100 dark:bg-green-900 px-1 rounded text-xs">accessibilityStatementUrl</code> in the widget config.
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <code className="text-xs bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 px-2 py-1 rounded">
            {hostedUrl}
          </code>
          <button
            onClick={copyHostedUrl}
            className="px-3 py-1.5 text-xs font-medium bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
          >
            {copied ? "Copied!" : "Copy URL"}
          </button>
          <a
            href={hostedUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="px-3 py-1.5 text-xs font-medium border border-green-300 dark:border-green-700 text-green-700 dark:text-green-300 rounded-lg hover:bg-green-100 dark:hover:bg-green-900 transition-colors"
          >
            Preview
          </a>
        </div>
      </div>

      {/* Info banner */}
      <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-2xl p-5">
        <h3 className="font-semibold text-blue-900 dark:text-blue-200 mb-1">EAA Article 13 Compliance</h3>
        <p className="text-sm text-blue-700 dark:text-blue-300">
          The European Accessibility Act (EAA) requires all digital products and services to publish an accessibility statement. Generate one below, host it on your site, then paste the URL in the widget config to link it from your widget.
        </p>
      </div>

      {/* Scan status */}
      {lastScanAt && (
        <div className={`rounded-xl border p-4 text-sm ${
          lastScanViolations === 0
            ? "bg-green-50 dark:bg-green-950 border-green-200 dark:border-green-800 text-green-800 dark:text-green-300"
            : "bg-yellow-50 dark:bg-yellow-950 border-yellow-200 dark:border-yellow-800 text-yellow-800 dark:text-yellow-300"
        }`}>
          {lastScanViolations === 0
            ? `Last WCAG scan (${new Date(lastScanAt).toLocaleDateString()}) found no violations.`
            : `Last WCAG scan (${new Date(lastScanAt).toLocaleDateString()}) found ${lastScanViolations} potential violation(s). Consider resolving these before generating the statement.`}
        </div>
      )}

      {/* Form */}
      <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 p-6 space-y-4">
        <h3 className="font-semibold text-gray-900 dark:text-white">Statement Details</h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Contact Name
            </label>
            <input
              type="text"
              value={form.contactName}
              onChange={(e) => setForm((f) => ({ ...f, contactName: e.target.value }))}
              className="w-full px-3 py-2 text-sm rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Jane Smith"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Contact Email
            </label>
            <input
              type="email"
              value={form.contactEmail}
              onChange={(e) => setForm((f) => ({ ...f, contactEmail: e.target.value }))}
              className="w-full px-3 py-2 text-sm rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="accessibility@example.com"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Conformance Level
            </label>
            <select
              value={form.conformanceLevel}
              onChange={(e) => setForm((f) => ({ ...f, conformanceLevel: e.target.value }))}
              className="w-full px-3 py-2 text-sm rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="A">WCAG 2.1 Level A</option>
              <option value="AA">WCAG 2.1 Level AA (EAA required)</option>
              <option value="AAA">WCAG 2.1 Level AAA</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Review Date
            </label>
            <input
              type="date"
              value={form.reviewDate}
              onChange={(e) => setForm((f) => ({ ...f, reviewDate: e.target.value }))}
              className="w-full px-3 py-2 text-sm rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Known Limitations (optional)
          </label>
          <textarea
            value={form.limitations}
            onChange={(e) => setForm((f) => ({ ...f, limitations: e.target.value }))}
            rows={3}
            className="w-full px-3 py-2 text-sm rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
            placeholder="Describe any known accessibility barriers and your plan to fix them..."
          />
        </div>

        <div className="flex flex-wrap gap-3 pt-2">
          <button
            onClick={downloadHtml}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors"
          >
            Download HTML
          </button>
          <button
            onClick={() => setPreview((p) => !p)}
            className="px-4 py-2 bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 rounded-lg text-sm font-medium hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
          >
            {preview ? "Hide Preview" : "Preview"}
          </button>
        </div>
      </div>

      {/* Preview */}
      {preview && (
        <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 p-6">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-4">Preview</h3>
          <iframe
            srcDoc={html}
            className="w-full border border-gray-200 dark:border-gray-700 rounded-lg"
            style={{ height: 480 }}
            title="Accessibility statement preview"
          />
        </div>
      )}

      {/* Link to statement in widget */}
      <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 p-6 space-y-4">
        <h3 className="font-semibold text-gray-900 dark:text-white">Link in Widget</h3>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          After hosting the HTML file on your site, add the URL to your widget config so it appears as a link in the widget panel footer. You can also set it directly in the{" "}
          <a href={`/dashboard/sites/${siteId}`} className="text-blue-600 dark:text-blue-400 underline">
            Config tab
          </a>
          .
        </p>
        <div className="text-sm text-gray-600 dark:text-gray-400">
          Current URL:{" "}
          {currentStatementUrl ? (
            <a
              href={currentStatementUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 dark:text-blue-400 underline"
            >
              {currentStatementUrl}
            </a>
          ) : (
            <span className="text-gray-400 dark:text-gray-600 italic">Not set</span>
          )}
        </div>
        {saved && (
          <p className="text-sm text-green-600 dark:text-green-400">Saved.</p>
        )}
      </div>
    </div>
  );
}
