export const LANGUAGES = [
  { value: "en", label: "English" },
  { value: "tr", label: "Turkish (Türkçe)" },
  { value: "de", label: "German (Deutsch)" },
  { value: "fr", label: "French (Français)" },
  { value: "es", label: "Spanish (Español)" },
  { value: "it", label: "Italian (Italiano)" },
  { value: "pt", label: "Portuguese (Português)" },
  { value: "nl", label: "Dutch (Nederlands)" },
  { value: "ar", label: "Arabic (العربية) — RTL" },
  { value: "he", label: "Hebrew (עברית) — RTL" },
  { value: "fa", label: "Persian (فارسی) — RTL" },
  { value: "ur", label: "Urdu (اردو) — RTL" },
  { value: "zh", label: "Chinese (中文)" },
  { value: "ja", label: "Japanese (日本語)" },
  { value: "ko", label: "Korean (한국어)" },
  { value: "ru", label: "Russian (Русский)" },
  { value: "pl", label: "Polish (Polski)" },
  { value: "cs", label: "Czech (Čeština)" },
  { value: "da", label: "Danish (Dansk)" },
  { value: "fi", label: "Finnish (Suomi)" },
  { value: "el", label: "Greek (Ελληνικά)" },
  { value: "hu", label: "Hungarian (Magyar)" },
  { value: "ro", label: "Romanian (Română)" },
  { value: "sk", label: "Slovak (Slovenčina)" },
  { value: "sv", label: "Swedish (Svenska)" },
  { value: "uk", label: "Ukrainian (Українська)" },
  { value: "bg", label: "Bulgarian (Български)" },
  { value: "hr", label: "Croatian (Hrvatski)" },
  { value: "lt", label: "Lithuanian (Lietuvių)" },
  { value: "lv", label: "Latvian (Latviešu)" },
  { value: "et", label: "Estonian (Eesti)" },
  { value: "sl", label: "Slovenian (Slovenščina)" },
  { value: "sr", label: "Serbian (Српски)" },
  { value: "no", label: "Norwegian (Norsk)" },
  { value: "th", label: "Thai (ไทย)" },
  { value: "vi", label: "Vietnamese (Tiếng Việt)" },
  { value: "id", label: "Indonesian (Bahasa Indonesia)" },
  { value: "ms", label: "Malay (Bahasa Melayu)" },
  { value: "ca", label: "Catalan (Català)" },
  { value: "sq", label: "Albanian (Shqip)" },
  { value: "sw", label: "Swahili (Kiswahili)" },
] as const;
